using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.LowLevel;
using UnityEngine.SceneManagement;
[InitializeOnLoad]
public static class KVerification
{
 static KVerification(){EditorApplication.playModeStateChanged+=s=>{if(!SessionState.GetBool("K.Run",false))return;if(s==PlayModeStateChange.EnteredPlayMode)new GameObject("K verification").AddComponent<KRunner>();if(s==PlayModeStateChange.EnteredEditMode){SessionState.SetBool("K.Run",false);EditorApplication.Exit(SessionState.GetInt("K.Exit",1));}};}
 public static void Run(){string path="Validation/"+(Nightly.Tag.StartsWith("K1")?"K1-keys":Nightly.Tag.StartsWith("K2")?"K2-camera":"S2-03-retry")+(Nightly.Tag.Contains("rerun")?"-rerun":"")+".txt";if(File.Exists(path))throw new IOException("Preserve evidence");SessionState.SetString("K.Path",path);SessionState.SetBool("K.Run",true);EditorSceneManager.OpenScene(Nightly.Tag.StartsWith("K1")?"Assets/Scenes/Menu.unity":"Assets/Scenes/A03.unity");EditorApplication.delayCall+=()=>EditorApplication.isPlaying=true;}
}
public sealed class KRunner:MonoBehaviour
{
 readonly List<string> lines=new(),errors=new();Keyboard kb;
 void Check(bool ok,string m){if(!ok)throw new Exception(m);lines.Add("PASS: "+m);}
 void Log(string m,string s,LogType t){if(t is LogType.Error or LogType.Exception or LogType.Assert)errors.Add(m+s);}
 IEnumerator Start(){DontDestroyOnLoad(gameObject);Application.logMessageReceived+=Log;InputSystem.settings.backgroundBehavior=InputSettings.BackgroundBehavior.IgnoreFocus;InputSystem.settings.editorInputBehaviorInPlayMode=InputSettings.EditorInputBehaviorInPlayMode.AllDeviceInputAlwaysGoesToGameView;kb=InputSystem.AddDevice<Keyboard>();var stack=new Stack<IEnumerator>();stack.Push(Nightly.Tag.StartsWith("K1")?Keys():Nightly.Tag.StartsWith("K2")?CameraTests():GateTests());bool fail=false;while(stack.Count>0&&!fail){object next=null;try{if(!stack.Peek().MoveNext()){stack.Pop();continue;}next=stack.Peek().Current;}catch(Exception e){fail=true;lines.Add("FAIL: "+e);}if(next is IEnumerator child)stack.Push(child);else if(!fail)yield return next;}Application.logMessageReceived-=Log;InputSystem.RemoveDevice(kb);fail|=errors.Count>0;lines.AddRange(errors);lines.Insert(0,(fail?"FAIL":"PASS")+" "+Nightly.Tag);lines.Add("FAIL "+(fail?1:0));File.WriteAllLines(SessionState.GetString("K.Path",""),lines);SessionState.SetInt("K.Exit",fail?1:0);EditorApplication.isPlaying=false;}
 PlayerInputReader Player=>RoomSession.Instance.Player;
 Rigidbody2D Body=>Player.GetComponent<Rigidbody2D>();
 void Place(Vector2 p){Player.ClearTransientInput();Player.transform.position=p;Body.position=p;Body.linearVelocity=Vector2.zero;Physics2D.SyncTransforms();}
 IEnumerator KeysHeld(params Key[] keys){InputSystem.QueueStateEvent(kb,new KeyboardState(keys));yield return null;}
 IEnumerator Tap(Key key){yield return KeysHeld(key);yield return KeysHeld();}
 IEnumerator Wait(){double end=Time.realtimeSinceStartupAsDouble+5;while(RoomSession.Instance.Transitioning||RoomSession.Instance.Respawning){if(Time.realtimeSinceStartupAsDouble>end)throw new Exception("transition timeout");yield return null;}}
 IEnumerator Keys(){
  yield return new WaitForSeconds(.25f);ProgressSave.Write(new ProgressData{dash=true,checkpointId="CP-A01"});SceneManager.LoadScene("Menu");yield return new WaitForSeconds(.25f);var menu=FindFirstObjectByType<SaveMenu>();Check(menu.CanContinue,"Menu valid isolated save");yield return Tap(UnityEngine.InputSystem.Key.DownArrow);yield return Tap(UnityEngine.InputSystem.Key.Z);Check(menu.Confirming,"Menu Z opens new-game confirmation");yield return Tap(UnityEngine.InputSystem.Key.X);Check(!menu.Confirming,"Menu X cancels");yield return Tap(UnityEngine.InputSystem.Key.Z);yield return Tap(UnityEngine.InputSystem.Key.Z);yield return new WaitForSeconds(.4f);Check(RoomSession.Instance.CurrentRoomId=="A01","Menu Z confirms new game");ProgressSave.Enabled=false;
  Check(RoomSession.Instance.RequestTransition("CombatTest","Assets/Scenes/Test/CombatTest.unity","Entry"),"enter isolated test room");yield return Wait();yield return new WaitForSeconds(.25f);Player.GetComponent<PlayerDash>().hasDash=true;
  foreach(var k in new[]{UnityEngine.InputSystem.Key.LeftArrow,UnityEngine.InputSystem.Key.RightArrow,UnityEngine.InputSystem.Key.A,UnityEngine.InputSystem.Key.D}){Place(new Vector2(6,1.81f));yield return KeysHeld();yield return new WaitForSeconds(.15f);yield return KeysHeld(k);yield return new WaitForFixedUpdate();Check(Mathf.Abs(Player.Move.x)>.9f&&Mathf.Sign(Body.linearVelocity.x)==(k==UnityEngine.InputSystem.Key.LeftArrow||k==UnityEngine.InputSystem.Key.A?-1:1),"move "+k);yield return KeysHeld();}
  float zShort=0,zLong=0,spaceShort=0,spaceLong=0;
  foreach(var key in new[]{UnityEngine.InputSystem.Key.Z,UnityEngine.InputSystem.Key.Space})foreach(float hold in new[]{.10f,.5f}){Place(new Vector2(6,1.81f));yield return KeysHeld();yield return new WaitForSeconds(.3f);float peak=Body.position.y,start=peak;yield return KeysHeld(key);double end=Time.realtimeSinceStartupAsDouble+hold;while(Time.realtimeSinceStartupAsDouble<end){peak=Mathf.Max(peak,Body.position.y);yield return null;}yield return KeysHeld();end=Time.realtimeSinceStartupAsDouble+.9;while(Time.realtimeSinceStartupAsDouble<end){peak=Mathf.Max(peak,Body.position.y);yield return null;}float height=peak-start;lines.Add($"MEASURE {key} hold={hold:F2}s height={height:F3}u");if(key==UnityEngine.InputSystem.Key.Z){if(hold<.2f)zShort=height;else zLong=height;}else{if(hold<.2f)spaceShort=height;else spaceLong=height;}}
  Check(zLong>zShort+.3f&&Mathf.Abs(zShort-spaceShort)<.1f&&Mathf.Abs(zLong-spaceLong)<.1f,"Z short/long jump and Space equivalent heights");
  foreach(var key in new[]{UnityEngine.InputSystem.Key.X,UnityEngine.InputSystem.Key.J}){yield return new WaitForSeconds(.4f);yield return KeysHeld(key);Check(Player.GetComponent<PlayerAttack>().Attacking,"attack "+key);yield return KeysHeld();}
  foreach(var key in new[]{UnityEngine.InputSystem.Key.C,UnityEngine.InputSystem.Key.K,UnityEngine.InputSystem.Key.LeftShift}){Place(new Vector2(6,1.81f));yield return new WaitForSeconds(.6f);yield return KeysHeld(key);yield return new WaitForFixedUpdate();Check(Player.GetComponent<PlayerDash>().IsDashing,"dash "+key);yield return KeysHeld();}
  Player.SetPaused(true);yield return Tap(UnityEngine.InputSystem.Key.Z);Check(!Player.Paused,"UI Z resumes Pause");Player.SetPaused(true);yield return Tap(UnityEngine.InputSystem.Key.X);Check(!Player.Paused,"UI X cancels Pause");
  var baseline=JsonUtility.FromJson<BindingSnapshot>("{}");var asset=AssetDatabase.LoadAssetAtPath<InputActionAsset>("Assets/Input/PlayerControls.inputactions");foreach(var binding in asset.bindings){Check(!binding.path.Contains("leftCtrl"),"LCtrl remains unbound");if(binding.path.StartsWith("<Gamepad>"))lines.Add("MEASURE unchanged gamepad "+binding.action+"="+binding.path);}
 }
 [Serializable]class BindingSnapshot{}
 IEnumerator CameraTests(){yield return null;yield break;}
 IEnumerator GateTests(){
  yield return new WaitForSeconds(.3f);QualitySettings.vSyncCount=0;Application.targetFrameRate=60;ProgressSave.Enabled=false;var dash=Player.GetComponent<PlayerDash>();var hp=Player.GetComponent<PlayerHealth>();var playerCollider=Player.GetComponent<BoxCollider2D>();
  foreach(int direction in new[]{1,-1})foreach(bool owned in new[]{false,true})foreach(bool jump in new[]{false,true}){
   dash.hasDash=owned;yield return KeysHeld();Place(new Vector2(direction>0?15.2f:17.8f,5.81f));yield return new WaitForSeconds(.6f);yield return KeysHeld(direction>0?UnityEngine.InputSystem.Key.RightArrow:UnityEngine.InputSystem.Key.LeftArrow,jump?UnityEngine.InputSystem.Key.Z:UnityEngine.InputSystem.Key.None);yield return new WaitForSeconds(.35f);lines.Add($"MEASURE gate direction={direction} owned={owned} jump={jump} position={Body.position}");Check(direction>0?Body.position.x<16:Body.position.x>17,"gate blocks walk/jump both directions, owned="+owned);yield return KeysHeld();
  }
  foreach(int direction in new[]{1,-1}){
   dash.hasDash=false;Place(new Vector2(direction>0?15.2f:17.8f,5.81f));yield return new WaitForSeconds(.6f);yield return KeysHeld(direction>0?UnityEngine.InputSystem.Key.RightArrow:UnityEngine.InputSystem.Key.LeftArrow,UnityEngine.InputSystem.Key.C);yield return new WaitForSeconds(.3f);Check(!dash.IsDashing&&(direction>0?Body.position.x<16:Body.position.x>17),"unowned Dash blocked direction "+direction);yield return KeysHeld();
   hp.RestoreMax();Place(new Vector2(direction>0?15.55f:17.45f,5.81f));yield return new WaitForSeconds(.2f);Check(hp.TakeDamage(1,new Vector2(direction>0?14:19,5.8f)),"knockback setup");yield return new WaitForSeconds(.1f);Check(direction>0?Body.position.x<16:Body.position.x>17,"knockback blocked direction "+direction);hp.RestoreMax();
   dash.hasDash=true;Place(new Vector2(direction>0?15.2f:17.8f,5.81f));yield return new WaitForSeconds(.6f);yield return KeysHeld(direction>0?UnityEngine.InputSystem.Key.RightArrow:UnityEngine.InputSystem.Key.LeftArrow,UnityEngine.InputSystem.Key.C);yield return new WaitForFixedUpdate();Check(dash.IsDashing,"owned Dash starts direction "+direction);yield return KeysHeld();yield return new WaitForSeconds(.2f);lines.Add($"MEASURE Dash through gate direction={direction} position={Body.position}");Check(direction>0?Body.position.x>17:Body.position.x<16,"owned Dash passes direction "+direction);var gate=FindFirstObjectByType<DashGate>().GetComponent<BoxCollider2D>();Check(!Physics2D.GetIgnoreCollision(gate,playerCollider)&&gate.enabled,"collision restored, gate not removed");
  }
  var gateBounds=FindFirstObjectByType<DashGate>().GetComponent<BoxCollider2D>().bounds;var shelfBounds=GameObject.Find("A03_Shelf").GetComponent<BoxCollider2D>().bounds;lines.Add($"MEASURE gate min/max={gateBounds.min}/{gateBounds.max}; shelf top={shelfBounds.max.y}");
  Place(new Vector2(24,1.81f));yield return KeysHeld();yield return new WaitForSeconds(.3f);yield return KeysHeld(UnityEngine.InputSystem.Key.Z);float feetMax=Body.position.y-.8f;double until=Time.realtimeSinceStartupAsDouble+.9;while(Time.realtimeSinceStartupAsDouble<until){feetMax=Mathf.Max(feetMax,Body.position.y-.8f);yield return null;}yield return KeysHeld();lines.Add($"MEASURE floor under right shelf jump max feet={feetMax:F3}u; shelf top=5u; gate height=6u");Check(feetMax<5&&gateBounds.size.y>Player.GetComponent<PlayerMotor>().Tuning.jumpVelocity*Player.GetComponent<PlayerMotor>().Tuning.jumpVelocity/(2*Player.GetComponent<PlayerMotor>().Tuning.gravity),"right shelf unreachable directly from floor; gate too tall for ordinary jump");
  var exits=FindObjectsByType<RoomExit>(FindObjectsSortMode.None);var shelfExit=Array.Find(exits,e=>e.destinationRoomId=="B01");var floorExit=Array.Find(exits,e=>e.destinationRoomId=="A04");var room=FindFirstObjectByType<RoomDefinition>();Check(room.TryGetSpawn("FromShelf",out var spawn),"FromShelf authored");var eb=shelfExit.GetComponent<BoxCollider2D>().bounds;var fb=floorExit.GetComponent<BoxCollider2D>().bounds;lines.Add($"MEASURE shelf exit={eb.min}/{eb.max}, floor exit={fb.min}/{fb.max}, spawn={spawn.transform.position}; wall separation={35-eb.max.x:F3}u");Check(fb.max.y<4&&!fb.Intersects(eb)&&!eb.Intersects(new Bounds(spawn.transform.position,new Vector3(.7f,1.6f,0)))&&35-eb.max.x>=4,"floor/shelf exits and FromShelf do not overlap; wall clear");
  foreach(string to in new[]{"B01","A03","B01"})yield return ExitTo(to);
  var cp=FindFirstObjectByType<Checkpoint>();Check(cp.checkpointId=="CP-B01","B01 checkpoint unique");Place(cp.transform.position);yield return new WaitForSeconds(.15f);Check(RoomSession.Instance.CheckpointId=="CP-B01","physical CP-B01 activation");Check(RoomSession.Instance.Die(),"B01 death accepted");yield return Wait();Check(RoomSession.Instance.CurrentRoomId=="B01"&&hp.HP==5&&Vector2.Distance(Body.position,cp.spawn.transform.position)<.15f,"B01 death returns safely");
  foreach(var exit in FindObjectsByType<RoomExit>(FindObjectsSortMode.None))Check(!exit.GetComponent<BoxCollider2D>().bounds.Intersects(new Bounds(cp.spawn.transform.position,new Vector3(.7f,1.6f,0))),"B01 spawn does not overlap exit");
  lines.Add("PASS evidence: ordinary wall cancellation at 30/60/120fps = Validation/Verification-night-T1-S2-01.txt (DashTest, away from A03 exits).");
 }
 IEnumerator ExitTo(string to){RoomExit exit=null;foreach(var e in FindObjectsByType<RoomExit>(FindObjectsSortMode.None))if(e.destinationRoomId==to)exit=e;Check(exit!=null,"exit exists to "+to);string id=exit.destinationSpawnId;Place(exit.GetComponent<BoxCollider2D>().bounds.center);yield return new WaitForFixedUpdate();yield return null;yield return Wait();Check(RoomSession.Instance.CurrentRoomId==to,"physical exit to "+to);var room=FindFirstObjectByType<RoomDefinition>();Check(room.TryGetSpawn(id,out var spawn),"arrival ID "+id);lines.Add("MEASURE arrival "+to+"/"+id+" expected="+spawn.transform.position+" actual="+Body.position);Check(Vector2.Distance(Body.position,spawn.transform.position)<.15f,"safe arrival "+to);}
}
