using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.LowLevel;
using UnityEngine.SceneManagement;

[InitializeOnLoad]
public static class S3Verification
{
    static S3Verification(){EditorApplication.playModeStateChanged+=s=>{if(!SessionState.GetBool("S3.Run",false))return;if(s==PlayModeStateChange.EnteredPlayMode)new GameObject("S3 verification").AddComponent<S3Runner>();if(s==PlayModeStateChange.EnteredEditMode){SessionState.SetBool("S3.Run",false);EditorApplication.Exit(SessionState.GetInt("S3.Exit",1));}};}
    public static void Run(){string stem=Nightly.Tag;string path="Validation/"+stem+".txt";if(File.Exists(path))throw new IOException("Preserve evidence");SessionState.SetString("S3.Path",path);SessionState.SetBool("S3.Run",true);EditorSceneManager.OpenScene(stem.StartsWith("S3-03")?"Assets/Scenes/B01.unity":stem.StartsWith("S3-02")?"Assets/Scenes/Test/CombatTest.unity":"Assets/Scenes/Test/DoubleJumpTest.unity");EditorApplication.delayCall+=()=>EditorApplication.isPlaying=true;}
}
public sealed class S3Runner:MonoBehaviour
{
    readonly List<string> lines=new(),errors=new();Keyboard kb;
    PlayerInputReader Player=>RoomSession.Instance.Player;
    Rigidbody2D Body=>Player.GetComponent<Rigidbody2D>();
    PlayerMotor Motor=>Player.GetComponent<PlayerMotor>();
    void Check(bool ok,string m){if(!ok)throw new Exception(m);lines.Add("PASS: "+m);}
    void Log(string m,string s,LogType t){if(t is LogType.Error or LogType.Exception or LogType.Assert)errors.Add(m+s);}
    IEnumerator Start(){DontDestroyOnLoad(gameObject);Application.logMessageReceived+=Log;InputSystem.settings.backgroundBehavior=InputSettings.BackgroundBehavior.IgnoreFocus;InputSystem.settings.editorInputBehaviorInPlayMode=InputSettings.EditorInputBehaviorInPlayMode.AllDeviceInputAlwaysGoesToGameView;kb=InputSystem.AddDevice<Keyboard>();var stack=new Stack<IEnumerator>();stack.Push(Nightly.Tag.StartsWith("S3-03")?B01B02():Nightly.Tag.StartsWith("S3-02")?E2():DoubleJump());bool fail=false;while(stack.Count>0&&!fail){object next=null;try{if(!stack.Peek().MoveNext()){stack.Pop();continue;}next=stack.Peek().Current;}catch(Exception e){fail=true;lines.Add("FAIL: "+e);}if(next is IEnumerator child)stack.Push(child);else if(!fail)yield return next;}Application.logMessageReceived-=Log;InputSystem.RemoveDevice(kb);fail|=errors.Count>0;lines.AddRange(errors);lines.Insert(0,(fail?"FAIL":"PASS")+" "+Nightly.Tag+" Unity="+Application.unityVersion);lines.Add("Error/Exception/Assert "+errors.Count);File.WriteAllLines(SessionState.GetString("S3.Path",""),lines);SessionState.SetInt("S3.Exit",fail?1:0);EditorApplication.isPlaying=false;}
    void EnemyPlace(EnemyCharger e,Vector2 p){e.transform.position=p;e.GetComponent<Rigidbody2D>().position=p;e.GetComponent<Rigidbody2D>().linearVelocity=Vector2.zero;Physics2D.SyncTransforms();}
    IEnumerator Until(Func<bool> condition,float timeout=4){double end=Time.realtimeSinceStartupAsDouble+timeout;while(!condition()){CheckTimeout(end);yield return new WaitForFixedUpdate();}}
    void CheckTimeout(double end){if(Time.realtimeSinceStartupAsDouble>end)throw new Exception("timeout");}
    IEnumerator ExitTo(string target){RoomExit exit=null;foreach(var e in FindObjectsByType<RoomExit>(FindObjectsSortMode.None))if(e.destinationRoomId==target)exit=e;Check(exit!=null&&exit.enabled,"enabled exit to "+target);string spawnId=exit.destinationSpawnId;Place(exit.GetComponent<BoxCollider2D>().bounds.center);yield return new WaitForFixedUpdate();yield return null;yield return Until(()=>!RoomSession.Instance.Transitioning);Check(RoomSession.Instance.CurrentRoomId==target,"physical door to "+target);var room=FindFirstObjectByType<RoomDefinition>();Check(room.TryGetSpawn(spawnId,out var spawn)&&Vector2.Distance(Body.position,spawn.transform.position)<.2f,"safe arrival "+target+"/"+spawnId);}
    IEnumerator LedgeAttempt(bool owned,bool dash){Motor.hasDoubleJump=owned;Player.GetComponent<PlayerDash>().hasDash=true;yield return Keys();Place(new Vector2(23.5f,1.81f));yield return new WaitForSeconds(.3f);yield return Keys(UnityEngine.InputSystem.Key.RightArrow,UnityEngine.InputSystem.Key.Z);yield return new WaitForSeconds(.26f);if(owned){yield return Keys(UnityEngine.InputSystem.Key.RightArrow);yield return Keys(UnityEngine.InputSystem.Key.RightArrow,UnityEngine.InputSystem.Key.Z);}else if(dash){yield return Keys(UnityEngine.InputSystem.Key.RightArrow,UnityEngine.InputSystem.Key.Z,UnityEngine.InputSystem.Key.C);}float max=Body.position.y-.8f;double end=Time.realtimeSinceStartupAsDouble+.65;while(Time.realtimeSinceStartupAsDouble<end){max=Mathf.Max(max,Body.position.y-.8f);yield return null;}yield return Keys();lines.Add($"MEASURE B01 owned={owned} dash={dash} max feet={max:F3} final={Body.position}");if(owned)Check(Body.position.x>=26&&Body.position.y-.8f>=4.55f,"double jump reaches G-J ledge with specified input");else Check(max<4.6f&&Body.position.y-.8f<4.6f,"unowned jump/dash cannot reach ledge");}
    IEnumerator B01B02(){yield return new WaitForSeconds(.3f);ProgressSave.Enabled=false;yield return LedgeAttempt(false,false);yield return LedgeAttempt(false,true);yield return LedgeAttempt(true,false);var exits=FindObjectsByType<RoomExit>(FindObjectsSortMode.None);RoomExit upper=Array.Find(exits,e=>e.exitId=="Upper"),lower=Array.Find(exits,e=>e.exitId=="Right");var ub=upper.GetComponent<BoxCollider2D>().bounds;var lb=lower.GetComponent<BoxCollider2D>().bounds;lines.Add($"MEASURE upper={ub.min}/{ub.max}, lower={lb.min}/{lb.max}");Check(!ub.Intersects(lb)&&!upper.enabled,"nonoverlapping exits; upper disabled until B05 exists");yield return ExitTo("B02");var e=FindFirstObjectByType<EnemyCharger>();Check(e!=null&&e.HP==3,"B02 E2 authored");Place(new Vector2(11,3.81f));yield return new WaitForSeconds(.25f);Check(Motor.Grounded&&Player.GetComponent<PlayerHealth>().HP==5,"safe introduction platform");Place(new Vector2(20,1.81f));yield return Until(()=>e.State==EnemyCharger.Phase.Warning);Check(e.Direction==-1,"B02 warning faces approaching player");Place(new Vector2(10,3.81f));yield return Until(()=>e.State==EnemyCharger.Phase.Recovery);Check(Player.GetComponent<PlayerHealth>().HP==5,"step offers safe charge escape");for(int i=0;i<3;i++){EnemyPlace(e,new Vector2(24,1.51f));Place(new Vector2(22.9f,1.81f));yield return Keys(UnityEngine.InputSystem.Key.RightArrow);yield return Keys(UnityEngine.InputSystem.Key.X);yield return Keys();yield return new WaitForSeconds(.45f);}Check(e==null,"B02 E2 three attack defeat");yield return ExitTo("B01");yield return ExitTo("B02");Check(FindFirstObjectByType<EnemyCharger>()?.HP==3,"B02 reentry resets E2");yield return ExitTo("B01");var cp=FindFirstObjectByType<Checkpoint>();Place(cp.transform.position);yield return new WaitForSeconds(.2f);Check(RoomSession.Instance.CheckpointId=="CP-B01","CP-B01 physical activation");Check(RoomSession.Instance.Die(),"CP-B01 death request");yield return Until(()=>!RoomSession.Instance.Respawning);Check(RoomSession.Instance.CurrentRoomId=="B01"&&Vector2.Distance(Body.position,cp.spawn.transform.position)<.2f,"CP-B01 safe death return");}
    IEnumerator E2(){yield return new WaitForSeconds(.3f);ProgressSave.Enabled=false;foreach(var old in FindObjectsByType<EnemyRespawn>(FindObjectsSortMode.None))old.gameObject.SetActive(false);foreach(var old in FindObjectsByType<EnemyPatrol>(FindObjectsSortMode.None))old.gameObject.SetActive(false);foreach(var old in FindObjectsByType<DamageBlock>(FindObjectsSortMode.None))old.gameObject.SetActive(false);foreach(var old in FindObjectsByType<DummyTarget>(FindObjectsSortMode.None))old.gameObject.SetActive(false);lines.Add("NOTE: unrelated CombatTest fixtures disabled only in this verification run; first charge was obstructed by E1 patrol");var e=FindFirstObjectByType<EnemyCharger>();Place(new Vector2(18,1.81f));yield return new WaitForSeconds(.3f);Check(e.State==EnemyCharger.Phase.Idle,"outside 5u detection waits");Place(new Vector2(21,1.81f));yield return Until(()=>e.State==EnemyCharger.Phase.Warning);double started=Time.timeAsDouble;int direction=e.Direction;Color before=e.GetComponent<SpriteRenderer>().color;yield return new WaitForSeconds(.15f);Check(e.GetComponent<SpriteRenderer>().color!=before,"visible warning changes color");Place(new Vector2(30,1.81f));yield return Until(()=>e.State==EnemyCharger.Phase.Charge);float x=e.transform.position.x;double chargeAt=Time.timeAsDouble;lines.Add($"MEASURE warning={chargeAt-started:F3}s");Check(Math.Abs(chargeAt-started-.6)<.06,"0.6s warning");yield return Until(()=>e.State==EnemyCharger.Phase.Recovery);float distance=Mathf.Abs(e.transform.position.x-x);lines.Add($"MEASURE charge duration={Time.timeAsDouble-chargeAt:F3}s distance={distance:F3}u");Check(e.Direction==direction&&distance>2.15f&&distance<2.55f,"fixed direction 0.4s charge at 6u/s");double recoverAt=Time.timeAsDouble;yield return Until(()=>e.State==EnemyCharger.Phase.Idle);Check(Math.Abs(Time.timeAsDouble-recoverAt-1)<.06,"1s recovery");
        EnemyPlace(e,new Vector2(2,1.81f));Place(new Vector2(1.3f,1.81f));yield return Until(()=>e.State==EnemyCharger.Phase.Warning);Place(new Vector2(7,1.81f));yield return Until(()=>e.State==EnemyCharger.Phase.Recovery);Check(e.transform.position.x>1.2f,"wall stops charger");
        Place(new Vector2(20,1.81f));Player.GetComponent<PlayerHealth>().RestoreMax();yield return null;e=FindFirstObjectByType<EnemyCharger>();EnemyPlace(e,new Vector2(20,1.81f));yield return new WaitForFixedUpdate();yield return null;var hp=Player.GetComponent<PlayerHealth>();Check(hp.HP==4&&hp.Invincible,"contact damage one and invincibility");int health=hp.HP;yield return new WaitForSeconds(.15f);Check(hp.HP==health,"invincibility rejects repeated contact");Place(new Vector2(21,1.81f));hp.RestoreMax();yield return null;e=FindFirstObjectByType<EnemyCharger>();EnemyPlace(e,new Vector2(25,1.81f));Player.GetComponent<PlayerDash>().hasDash=true;yield return Until(()=>e.State==EnemyCharger.Phase.Warning);yield return Keys(UnityEngine.InputSystem.Key.LeftArrow,UnityEngine.InputSystem.Key.C);yield return new WaitForSeconds(.25f);yield return Keys();yield return new WaitForSeconds(.8f);Check(hp.HP==5,"dash increases separation to evade charge; no invulnerability claim");
        for(int i=0;i<3;i++){EnemyPlace(e,new Vector2(15,1.81f));Place(new Vector2(13.9f,1.81f));yield return Keys(UnityEngine.InputSystem.Key.RightArrow);yield return Keys(UnityEngine.InputSystem.Key.X);yield return Keys();yield return new WaitForSeconds(.25f);if(i<2){Check(e!=null&&e.HP==2-i,"attack reduces E2 HP "+i);Check(Mathf.Abs(e.LastHitVelocity.x)==3,"received knockback 3u/s");}yield return new WaitForSeconds(.2f);}Check(e==null,"three attacks destroy E2");Check(RoomSession.Instance.Die(),"death reset request");yield return new WaitForSeconds(.9f);Check(FindFirstObjectByType<EnemyCharger>()?.HP==3,"death restores E2 HP and idle state");
        Check(RoomSession.Instance.RequestTransition("A01","Assets/Scenes/A01.unity","Entry"),"leave CombatTest");yield return Until(()=>!RoomSession.Instance.Transitioning);Check(RoomSession.Instance.RequestTransition("CombatTest","Assets/Scenes/Test/CombatTest.unity","Entry"),"reenter CombatTest");yield return Until(()=>!RoomSession.Instance.Transitioning);yield return new WaitForSeconds(.2f);Check(FindFirstObjectByType<EnemyCharger>()?.HP==3,"reentry resets E2");
    }
    void Place(Vector2 p){Player.ClearTransientInput();Player.transform.position=p;Body.position=p;Body.linearVelocity=Vector2.zero;Physics2D.SyncTransforms();}
    IEnumerator Keys(params Key[] keys){InputSystem.QueueStateEvent(kb,new KeyboardState(keys));yield return null;yield return new WaitForFixedUpdate();}
    IEnumerator Settle(){yield return Keys();Place(new Vector2(10,1.81f));yield return new WaitForSeconds(.3f);Check(Motor.Grounded,"settled on floor");}
    float normalMax,doubleMax;
    IEnumerator Measure(bool twice,int fps){yield return Settle();int count=Motor.DoubleJumpsPerformed;yield return Keys(UnityEngine.InputSystem.Key.Z);float max=Body.position.y-.8f;double end=Time.realtimeSinceStartupAsDouble+.35;while(Time.realtimeSinceStartupAsDouble<end){max=Mathf.Max(max,Body.position.y-.8f);yield return null;}if(twice){yield return Keys();yield return Keys(UnityEngine.InputSystem.Key.Z);}end=Time.realtimeSinceStartupAsDouble+.6;while(Time.realtimeSinceStartupAsDouble<end){max=Mathf.Max(max,Body.position.y-.8f);yield return null;}yield return Keys();float height=max-1;lines.Add($"MEASURE fps={fps} double={twice} max feet={max:F3} height above floor={height:F3}u");if(twice){doubleMax=height;Check(Motor.DoubleJumpsPerformed==count+1,"one additional jump");}else{normalMax=height;Check(Motor.DoubleJumpsPerformed==count,"hold never triggers double jump");}}
    IEnumerator DoubleJump(){yield return new WaitForSeconds(.3f);ProgressSave.Enabled=false;QualitySettings.vSyncCount=0;Check(Motor.hasDoubleJump,"test player owned true");Check(!AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Prefabs/Player.prefab").GetComponent<PlayerMotor>().hasDoubleJump,"production player ownership false");foreach(int fps in new[]{30,60,120}){Application.targetFrameRate=fps;yield return Measure(false,fps);yield return Measure(true,fps);Check(3.6f>=normalMax+.8f&&3.6f<=doubleMax-.5f,"G-J 3.6 within measured margins");}
        Application.targetFrameRate=60;yield return Settle();yield return Keys(UnityEngine.InputSystem.Key.Z);yield return new WaitForSeconds(.15f);yield return Keys();yield return Keys(UnityEngine.InputSystem.Key.Z);int used=Motor.DoubleJumpsPerformed;yield return Keys();yield return Keys(UnityEngine.InputSystem.Key.Z);Check(Motor.DoubleJumpsPerformed==used&&Body.linearVelocity.y<12,"third jump impossible");
        Player.GetComponent<PlayerDash>().hasDash=true;yield return Keys(UnityEngine.InputSystem.Key.C);yield return new WaitForSeconds(.2f);yield return Keys();yield return Keys(UnityEngine.InputSystem.Key.Z);Check(Motor.DoubleJumpsPerformed==used,"dash does not restore double jump");
        Place(new Vector2(10,7));yield return new WaitForSeconds(.15f);Check(!Motor.DoubleJumpAvailable,"transient input clear/airborne placement does not restore");yield return Settle();Place(new Vector2(10,7));yield return new WaitForSeconds(.15f);yield return Keys(UnityEngine.InputSystem.Key.Z);Check(Motor.DoubleJumpsPerformed==used+1,"walk-off beyond Coyote has one additional jump");
        Motor.hasDoubleJump=false;yield return Settle();Place(new Vector2(10,7));yield return new WaitForSeconds(.15f);used=Motor.DoubleJumpsPerformed;yield return Keys(UnityEngine.InputSystem.Key.Z);Check(Motor.DoubleJumpsPerformed==used,"unowned airborne jump ignored");yield return Keys();
        Check(ProgressSave.Write(new ProgressData{dash=true,doubleJump=true,checkpointId="CP-B01"}),"isolated save write");Check(ProgressSave.Continue(),"saved ownership load requested");Check(ProgressSave.PendingScene=="Assets/Scenes/B01.unity","Continue CP-B01 scene mapping");Destroy(RoomSession.Instance.gameObject);yield return null;SceneManager.LoadScene("B01");yield return new WaitForSeconds(.4f);Check(Motor.hasDoubleJump&&RoomSession.Instance.CheckpointId=="CP-B01","saved ownership applied to production player");
    }
}
